name: Update GeoJSON

on:
  schedule:
    - cron: '0 0 * * 0'  # '0 0 * * 0' Runs every week at midnight on Sunday
  workflow_dispatch:  # Allows manual triggering from the Actions tab

jobs:
  update-geojson:
    runs-on: ubuntu-latest

    
    services:
      postgres:
        image: postgres:latest
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        env:
          POSTGRES_DB: CVMAP25
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: 2525CVMAPAFGO$


    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install psycopg2-binary

      - name: Initialize database
        env:
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
        run: |
          export PGPASSWORD='2525CVMAPAFGO$'
          psql -h localhost -U postgres -d CVMAP25 -c "CREATE ROLE root WITH LOGIN SUPERUSER INHERIT CREATEDB CREATEROLE NOREPLICATION;"
          psql -h localhost -U postgres -d CVMAP25 -c "CREATE TABLE IF NOT EXISTS geo_data (id SERIAL PRIMARY KEY, location TEXT, title TEXT, date DATE, city TEXT, subtitle TEXT, description TEXT, more_info TEXT, latitude DOUBLE PRECISION, longitude DOUBLE PRECISION);"
      
      - name: Run fetchgeo.py
        env:
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
        run: python Dataprocess/fetchgeo.py
  
      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add Dataprocess/CVMAP.geojson
          git commit -m 'Update GeoJSON file'
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}