name: Update GeoJSON

on:
  schedule:
    - cron: '* * * * *'  # '0 0 * * 0' Runs every week at midnight on Sunday
  workflow_dispatch:  # Allows manual triggering from the Actions tab

jobs:
  update-geojson:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install psycopg2-binary

      - name: Run fetchgeo.py
        run: python Dataprocess/fetchgeo.py

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add Dataprocess/CVMAP.geojson
          git commit -m 'Update GeoJSON file'
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}